Documentation:
  Enabled: false
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'lib/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
      # too many lines in blocks
    - 'spec/rails_helper.rb'
    - 'spec/features/submitting_application_spec.rb'
    - 'spec/features/listing_petitions_spec.rb'
    - 'spec/features/show_petitions_spec.rb'
    - 'spec/requests/petitions_spec.rb'
    - 'spec/features/editing_petition_spec.rb'
    - 'app/controllers/petitions_controller.rb'
    - 'Guardfile'
    - 'Gemfile'
      # other configuration
      # # ...

